### PR TITLE
Backport ControlScripts to enable Vehicle Support

### PR DESCRIPTION
**Pull request by Cristiano100**

### CODE REVIEW

**Comment by Cristiano100** [comment]
1.6v support for Vehicle control in years earlier than Late 2015

**Comment by CitizenFoffie** [comment]
Why was vehicle control broken?

**Comment by Cristiano100** [comment]
There was no support for it.

**Comment by p0s0** [comment]
to review tomorrow

**Comment by CitizenFoffie** [comment]
I reviewed it, it adds a official roblox module written by the head of their App team.

**Comment by p0s0** [comment]
reviewed, @Cristiano100 can you put the new MainModule inside of a new v1.6.1 folder? i can fill out the README.md if you'd like

v1.6.2 will have a new speedometer for earlier versions before it was updated

**Comment by Cristiano100** [comment]
Accidentally put "1.16" in commit message, files are named correctly.
image

**Comment by p0s0** [comment]
thanks, will merge in like 9 minutes

**Review by p0s0 — APPROVED** [review]
looks good

**Pull request merged**
